data:
    dataset: "IMAGES"               # 데이터셋 이름 (IMAGES)
    image_size: 64                  # 이미지 크기
    channels: 3                     # 채널 수 (3은 RGB를 의미)
    logit_transform: false          # 로짓 변환 사용 여부
    uniform_dequantization: false   # 균등 디퀀타이제이션 사용 여부
    gaussian_dequantization: false  # 가우시안 디퀀타이제이션 사용 여부
    random_flip: true               # 데이터 증강 (랜덤 플립)
    rescaled: true                  # 0-1 값을 -1~1로 스케일링
    num_workers: 4                  # DataLoader에서 사용할 워커 수

model:
    type: "simple"                  # 모델 유형
    in_channels: 3                  # 입력 채널 수
    out_ch: 3                       # 출력 채널 수
    ch: 128                         # 채널 크기
    ch_mult: [1, 2, 2, 2, 4]        # 채널 확장 비율
    num_res_blocks: 2               # Residual Block 수
    attn_resolutions: [16]          # 어텐션 적용 해상도
    dropout: 0.1                    # 드롭아웃 비율
    var_type: fixedlarge            # 분산 유형
    ema_rate: 0.9999                # EMA 비율
    ema: True                       # EMA 사용 여부
    resamp_with_conv: True          # Resampling 시 Conv 사용 여부

diffusion:
    beta_schedule: linear           # 베타 스케줄 (linear)
    beta_start: 0.0001              # 베타 시작값
    beta_end: 0.02                  # 베타 종료값
    num_diffusion_timesteps: 1000   # 확산 단계 수

training:
    batch_size: 64                  # 배치 크기
    n_epochs: 10000                 # 에폭 수
    snapshot_freq: 5000             # 체크포인트 저장 빈도
    validation_freq: 2000           # 검증 빈도

sampling:
    batch_size: 32                  # 샘플링 배치 크기
    last_only: True                 # 마지막 단계 샘플링만 저장 여부

optim:
    optimizer: "Adam"
    lr: 0.0002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0
    weight_decay: 0.0001  # 이 부분을 추가
